cluster.name: ${CLUSTER_NAME}
network.host: 0.0.0.0
xpack.monitoring.enabled: true
#xpack.security.enabled: false
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.ssl.certificate_authorities: /usr/share/elasticsearch/config/x-pack/certificates/ca/ca.crt
xpack.ssl.certificate: /usr/share/elasticsearch/config/x-pack/certificates/${EZMESURE_ES_NODE_NAME}/${EZMESURE_ES_NODE_NAME}.crt
xpack.ssl.key: /usr/share/elasticsearch/config/x-pack/certificates/${EZMESURE_ES_NODE_NAME}/${EZMESURE_ES_NODE_NAME}.key
xpack.ssl.verification_mode: "none"


xpack.notification.email.account:
  local_account:
    email_defaults:
      from: xpack@inist.fr
    profile: standard
    smtp:
      host: ${EZMESURE_SMTP_HOST}
      port: 25


# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
network.publish_host: ${EZMESURE_ES_PUBLISH}
node.name: ${EZMESURE_ES_NODE_NAME}
discovery.zen.ping.unicast.hosts: ${EZMESURE_ES_DISCOVERY}
discovery.zen.minimum_master_nodes: ${EZMESURE_ES_MINMASTER}
node.master: ${EZMESURE_ES_NODE_MASTER}
node.data: ${EZMESURE_ES_NODE_DATA}
node.ingest: ${EZMESURE_ES_NODE_INGEST}
search.remote.connect: ${EZMESURE_ES_NODE_SEARCH_REMOTE}
#bootstrap.memory_lock: true
path.logs: /usr/share/elasticsearch/logs

# Disallow searches with too many agregations
search.max_buckets: 10000
