cluster.name: ${CLUSTER_NAME}
network.host: 0.0.0.0
xpack.monitoring.enabled: true
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/x-pack/certificates/ca/ca.crt
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/x-pack/certificates/${EZMESURE_ES_NODE_NAME}/${EZMESURE_ES_NODE_NAME}.crt
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/x-pack/certificates/${EZMESURE_ES_NODE_NAME}/${EZMESURE_ES_NODE_NAME}.key

xpack.notification.email.account:
  local_account:
    email_defaults:
      from: xpack@inist.fr
    profile: standard
    smtp:
      host: ${EZMESURE_SMTP_HOST}
      port: 25


network.publish_host: ${EZMESURE_ES_PUBLISH}
node.name: ${EZMESURE_ES_NODE_NAME}
discovery.type: ${EZMESURE_ES_DISCOVERY_TYPE}
discovery.seed_hosts: ${EZMESURE_ES_DISCOVERY}
# initial_master_nodes must be set the very first time the cluster is started
cluster.initial_master_nodes: ${EZMESURE_ES_INITIAL_MASTER_NODES}
node.master: ${EZMESURE_ES_NODE_MASTER}
node.data: ${EZMESURE_ES_NODE_DATA}
node.ingest: ${EZMESURE_ES_NODE_INGEST}
cluster.remote.connect: ${EZMESURE_ES_NODE_SEARCH_REMOTE}
#bootstrap.memory_lock: true
path.logs: /usr/share/elasticsearch/logs

# Disallow searches with too many agregations
search.max_buckets: 10000

# api key
xpack.security.authc.api_key.enabled: true