version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http_proxy
      - https_proxy
      - CLUSTER_NAME=ezmesure
      - EZMESURE_ES_PUBLISH
      - EZMESURE_ES_NODE_NAME
      - EZMESURE_ES_DISCOVERY
      - EZMESURE_ES_NODE_MASTER
      - EZMESURE_ES_NODE_DATA
      - EZMESURE_ES_NODE_INGEST
      - EZMESURE_ES_NODE_SEARCH_REMOTE
      - EZMESURE_ES_MINMASTER
      - EZMESURE_SMTP_HOST
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${EZMESURE_ES_MEM_LIMIT}
    volumes:
      - "./data/elastic/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./elasticsearch/config/certificates:/usr/share/elasticsearch/config/x-pack/certificates"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    links:
      - elastic
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USERNAME
      - SERVER_BASEPATH
      - SERVER_HOST
      - SERVER_PORT
      - THIS_HOST
      - ELASTICSEARCH_URL
      - XPACK_MONITORING_ENABLED
      - KIBANA_DEFAULTAPPID
      - XPACK_REPORTING_KIBANASERVER_HOSTNAME
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    ports:
      - 3000:3000
    environment:
      - http_proxy
      - https_proxy
      - EZMESURE_ELASTIC_HOST=elastic
      - ELASTICSEARCH_PASSWORD
      - EZMESURE_AUTH_SECRET
      - EZMESURE_SMTP_HOST
      - EZMESURE_SMTP_PORT
      - EZMESURE_GOOGLE_EMAIL
      - EZMESURE_GOOGLE_PRIVATE_KEY
      - EZMESURE_NOTIFICATIONS_SENDER
      - EZMESURE_NOTIFICATIONS_CRON
      - EZMESURE_NOTIFICATIONS_RECIPIENTS
      - NODE_ENV
      - NODE_CONFIG
    links:
      - elastic
    volumes:
      - "./data/api/storage:/usr/src/app/storage"
    restart: unless-stopped

  front:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    ports:
      - 8080:8080
    environment:
      - API_URL=https://${EZMESURE_DOMAIN}.couperin.org/api
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped

  rp:
    build:
      context: ./rp
      args:
        - http_proxy
        - https_proxy
    ports:
      - 443:443
    environment:
      - http_proxy
      - https_proxy
      - APPLI_APACHE_SERVERNAME
      - APPLI_APACHE_SERVERADMIN
      - APPLI_APACHE_LOGLEVEL
    working_dir: /var/www/html
    volumes:
      - ./rp/shibboleth:/etc/shibboleth
      - ./rp/shibboleth/ssl:/etc/shibboleth/ssl
      - ./rp/apache2/sites-available:/etc/apache2/sites-available
      - ./rp/sp-log/:/var/log/shibboleth/
      - ./rp/sp-cache:/var/cache/shibboleth
    restart: unless-stopped
