version: '2'
services:
  elastic:
    extends:
      file: docker-compose.yml
      service: elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    links:
      - elastic
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USERNAME
      - SERVER_BASEPATH
      - SERVER_HOST
      - SERVER_PORT
      - THIS_HOST
      - ELASTICSEARCH_URL
      - XPACK_MONITORING_ENABLED
      - KIBANA_DEFAULTAPPID
      - XPACK_REPORTING_KIBANASERVER_HOSTNAME
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  rp:
    extends:
      file: docker-compose.yml
      service: rp

  api:
    image: node:10.15.3
    ports:
      - 3000:3000
    volumes:
      - "./api:/usr/src/app"
      - "./data/api/storage:/usr/src/app/storage"
    working_dir: /usr/src/app
    environment:
      - http_proxy
      - https_proxy
      - EZMESURE_ELASTIC_HOST=elastic
      - ELASTICSEARCH_PASSWORD
      - EZMESURE_AUTH_SECRET
      - EZMESURE_SMTP_HOST=maildev
      - EZMESURE_SMTP_PORT=25
      - EZMESURE_GOOGLE_EMAIL
      - EZMESURE_GOOGLE_PRIVATE_KEY
      - EZMESURE_NOTIFICATIONS_SENDER
      - EZMESURE_NOTIFICATIONS_CRON
      - EZMESURE_NOTIFICATIONS_RECIPIENTS
      - NODE_ENV
      - NODE_CONFIG
    links:
      - elastic
      - maildev
    restart: "no"
    command: npm run dev

  front:
    image: node:10.15.3
    ports:
      - 8080:8080
    volumes:
      - "./front:/usr/src/app"
    working_dir: /usr/src/app
    environment:
      - API_URL=https://${EZMESURE_DOMAIN}.couperin.org/api
      - HOST=0.0.0.0
      - PORT=8080
    command: npm run dev
    restart: "no"

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
